# Generated by Django 3.2.6 on 2021-11-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0005_auto_20211109_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='rating',
        ),
    ]
