# Generated by Django 5.1.1 on 2025-01-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(to='bookMng.book'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
